# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
