# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Item'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
