# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20180913_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
