# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_shoppingitem_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
